---

# This is the main task from which we call all subordinate tasks t

# Build the Peer2peer links between our Spines and Leaves.

- name: Build VLANS
  include_tasks: Build_VLANS.yml
  tags: vlans

- name: Build VXLAN tunnels
  include_tasks: Build_VXLAN_TUN.yml
  tags: vxlan
