---

# This is the main task from which we call all subordinate tasks t

# Build the Peer2peer links between our Spines and Leaves.

- name: Build P2P Links
  include_tasks: Build_P2P_Links.yml
  tags: p2p

- name: Build BGP Underlay
  include_tasks: Build_BGP_Underlay.yml
  tags: bgp
